services:
  lumen:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/apache2/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "5177:80"  # Map container's Apache2 port to host's port 8080
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: lumen_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3366:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata:
